#!/bin/bash

function cekKabisatMasehi() {
	if [ $(($1 % 400)) -eq 0 ]; then
		echo 1
	elif [ $(($1 % 100)) -eq 0 ]; then
		echo 0
	elif [ $(($1 % 4)) -eq 0 ]; then
		echo 1
	else
		echo 0
	fi
}

tahunKabisatHijriah=(2 5 7 10 13 15 18 21 24 26 29)

function cekKabisatHijriah() {
	if [[ " $1 " =~ " ${tahunKabisatHijriah[@]} " ]]; then
		echo 355
	else
		echo 354
	fi
}

hari=("Sabtu" "Minggu" "Senin" "Selasa" "Rabu" "Kamis" "Jumat")

function namaHari() {
	local angkaHari=$(($1 % 7))
	echo ${hari[$angkaHari]}
}

pasaran=("Legi" "Pahing" "Pon" "Wage" "Kliwon")

function namaPasaran() {
	local angkaPasaran=$(($1 % 5))
	echo ${pasaran[$angkaPasaran]}
}

# --------------------Masehi ke Hijriah---------------------------

hariMasehiKabisat=(31 29 31 30 31 30 31 31 30 31 30 31)
hariMasehiBiasa=(31 28 31 30 31 30 31 31 30 31 30 31)

function validasiTanggalMasehi() {
	if [ $(cekKabisatMasehi $1) -eq 1 ]; then
		if [ $3 -lt 1 ]; then
			echo 0
		elif [ $3 -gt ${hariMasehiKabisat[$(($2 - 1))]} ]; then
			echo 0
		else
			echo 1
		fi
	else
		if [ $3 -lt 1 ]; then
			echo 0
		elif [ $3 -gt ${hariMasehiBiasa[$(($2 - 1))]} ]; then
			echo 0
		else
			echo 1
		fi
	fi
}

function validasiMasehi() {
	if [ $2 -lt 1 ]; then
		echo 0
	elif [ $2 -gt 12 ]; then
		echo 0
	else 
		echo $(validasiTanggalMasehi $1 $2 $3)
	fi
}

function hariBulanMasehi() {
	local idx=0
	local hari=0
	if [ $(cekKabisatMasehi $1) -eq 1 ]; then
		until [ $idx -eq $2 ]; do
			let hari=$(($hari + ${hariMasehiKabisat[$idx]}))
			((idx++))
		done
	else
		until [ $idx -eq $2 ]; do
			let hari=$(($hari + ${hariMasehiBiasa[$idx]}))
			((idx++))
		done
	fi
}

function hariGregorian() {
	local tahunTam=$(($1 - 1))
	local sisaSiklus=$(($tahunTam % 4))
	local siklus=$(($tahunTam - $sisaSiklus))
	let siklus=$(($siklus / 4))
	let siklus=$(($siklus * 1461))
	let sisaSiklus=$(($sisaSiklus * 365))
	local bulan=$(hariBulanMasehi $1 $(($2 - 1)))
	echo $(($siklus + $sisaSiklus + $bulan + $3))
}

hariBulanHijriah=(29 30 29 30 29 30 29 30 29 30 29 30)
namaBulanHijriah=("Muharram" "Safar" "Rabiul Awal" "Rabiul Akhir" "Jumadil Awal" "Jumadil Akhir" "Rajab" "Syaban" "Ramadan" "Syawal" "Zulkaidah" "Zulhijjah")

function bulanKalenderMH() {
	local sisaHari=$2
	local idx=0
	while [ $sisaHari -gt ${hariBulanHijriah[$idx]} ]; do
		let sisaHari=$(($sisaHari - ${hariBulanHijriah[$idx]}))
		((idx++))
	done
	echo "$sisaHari ${namaBulanHijriah[$idx]} $1"
}

function kalenderMH() {
	local tahunHijriah=$(($1 * 30))
	local sisaHari=$2
	local idx=1
	local hariSetahun=0
	while [ $sisaHari -gt $(cekKabisatHijriah $idx) ]; do
		let hariSetahun=$(cekKabisatHijriah $idx)
		let sisaHari=$(($sisaHari - $hariSetahun))
		((tahunHijriah++))
		((idx++))
	done
	echo $(bulanKalenderMH $(($tahunHijriah + 1)) $sisaHari)
}

function intiMH() {
	local hariHijriah=$(($1 - 227029))
	local sisaDaur=$(($hariHijriah % 10631))
	local daurHijriah=$(($hariHijriah - $sisaDaur))
	let daurHijriah=$(($daurHijriah / 10631))
	echo $(kalenderMH $daurHijriah $sisaDaur)
}

function konversiDariMasehi() {
	if [ $(validasiMasehi $1 $2 $3) -eq 1 ]; then
		local angkaGregorian=$(hariGregorian $1 $2 $3)
		echo "$(namaHari $angkaGregorian) $(namaPasaran $angkaGregorian), $(intiMH $angkaGregorian) Hijriah"
	else
		echo "Error: Penanggalan Fiktif"
	fi
}

function mainMasehi() {
	echo "Masukkan tahun, bulan, tanggal dalam bentuk angka"
	read -p "Angka tahun : " tahun
	read -p "Angka bulan : " bulan
	read -p "Tanggal     : " tanggal
	echo ""
	echo "Hasil Konversi : $(konversiDariMasehi $tahun $bulan $tanggal)"
}

# --------------------Hijriah ke Masehi---------------------------

function validasiTanggalHijriah() {
	if [ $2 -lt 1 ]; then
		echo 0
	elif [ $2 -gt 30 ]; then
		echo 0
	else 
		echo 1
	fi
}

function validasiHijriah() {
	if [ $2 -lt 1 ]; then
		echo 0
	elif [ $2 -gt 12 ]; then
		echo 0
	else 
		echo $(validasiTanggalHijriah $1 $2 $3)
	fi
}

function hariDalamBulanHijriah() {
	local idx=0
	local hari=0
	until [ $idx -eq $1 ]; do
		let hari=$(($hari + ${hariBulanHijriah[$idx]}))
		((idx++))
	done
	echo $hari
}

function hariGregorianDariHijriah() {
	local tahunTam=$(($1 - 1))
	local sisaSiklus=$(($tahunTam % 30))
	local siklus=$(($tahunTam - $sisaSiklus))
	let siklus=$(($siklus / 30))
	let siklus=$(($siklus * 10631))
	local hariSisaSiklus=0
	local idx=0
	while [ $sisaSiklus -gt 0 ]; do
		let hariSisaSiklus=$(($(cekKabisatHijriah $idx) + $hariSisaSiklus))
		((sisaSiklus--))
		((idx++))
	done
	local bulan=$(hariDalamBulanHijriah $(($2 - 1)))
	echo $(($siklus + $hariSisaSiklus + $bulan + $3))
}

namaBulanMasehi=("Januari" "Februari" "Maret" "April" "Mei" "Juni" "Juli" "Agustus" "September" "Oktober" "November" "Desember")

function kalenderHM() {
	local idx=0
	local sisaHari=$2
	if [ $(cekKabisatMasehi $1) -eq 1 ]; then
		while [ $sisaHari -gt ${hariMasehiKabisat[$idx]} ]; do
			let sisaHari=$(($sisaHari - ${hariMasehiKabisat[$idx]}))
			((idx++))
		done
	else
		while [ $sisaHari -gt ${hariMasehiBiasa[$idx]} ]; do
			let sisaHari=$(($sisaHari - ${hariMasehiBiasa[$idx]}))
			((idx++))
		done
	fi
	echo "$sisaHari ${namaBulanMasehi[$idx]} $1"
}

function intiHM() {
	local sisaDaur=$(($1 % 1461))
	local daur=$(($1 - $sisaDaur))
	let daur=$(($daur / 1461))
	let daur=$(($daur * 4))
	local tahun=$(($sisaDaur % 365))
	let tahun=$(($sisaDaur - $tahun))
	let tahun=$(($tahun * 365))
	let tahun=$(($daur + $tahun + 1))
	let sisaDaur=$(($sisaDaur % 365))
	echo $(kalenderHM $tahun $sisaDaur)
}

function konversiDariHijriah() {
	if [ $(validasiHijriah $1 $2 $3) -eq 1 ]; then
		local angkaGregorian=$(($(hariGregorianDariHijriah $1 $2 $3) + 227029))
		echo "$(namaHari $angkaGregorian) $(namaPasaran $angkaGregorian), $(intiHM $angkaGregorian) Masehi"
	else
		echo "Error: Penanggalan Fiktif"
	fi
}

function mainHijriah() {
	echo "Masukkan tahun, bulan, tanggal dalam bentuk angka"
	read -p "Angka tahun : " tahun
	read -p "Angka bulan : " bulan
	read -p "Tanggal     : " tanggal
	echo ""
	echo "Hasil Konversi : $(konversiDariHijriah $tahun $bulan $tanggal)"
}

function main() {
	echo "Selamat datang, pilih menu: "
	echo "[1] Masehi ke Hijriah"
	echo "[2] Hijriah ke Masehi"
	echo ""
	read -p "Pilihan Anda : " pilih
	echo "------------------------------------------"
	case $pilih in
		1) mainMasehi;;
		2) mainHijriah;;
		*) echo "Unknown";;
	esac
}

main