#!/bin/bash

function luasPersegi() {
	echo $(($1 * $2))
}

echo "Masukkan panjang persegi :"
read panjang

echo "Masukkan lebar persegi :"
read lebar

echo "Luas persegi :"
echo $(luasPersegi $panjang $lebar)
